### ISSUE TITLE
# FRONT - agregar boton que genere otra card

### ISSUE THREAD

**Issue by masacr3** [masacr3/encuestapyme#2]
Se nesesita agregar un boton para generar una nueva card de Ingresos, Justificar donde pondrian el boton , y por que

**Comment by LucasAraujo639** [comment]
Pondria el boton en la parte inferior de forma estatica para mejorar la accesibilidad y la comodidad de los usuarios al utilizar la aplicación en dispositivos móviles, al hacerlo, los usuarios podrán acceder fácilmente al botón con el dedo pulgar, lo que mejorará la facilidad de uso y la experiencia del usuario.

**Comment by masacr3** [comment]
> Pondria el boton en la parte inferior de forma estatica para mejorar la accesibilidad y la comodidad de los usuarios al utilizar la aplicacion en dispositivos moviles, al hacerlo, los usuarios podran acceder facilmente al boton con el dedo pulgar, lo que mejorara la facilidad de uso y la experiencia del usuario.

Muy acertada la respuesta. La experiencia de usuario es fundamental para el desarrollo de algun componente , donde poner el boton es fundamental . ( LA RESPUESTA CITADA DEL DEDO PULGAR ) era requisito nesesario para Steve Job en la primera interfaz del iphone.
